const WORD_BANK = [

  // SPORT
  {cat:"Sport", a:"Calcio", b:"Rugby"},
  {cat:"Sport", a:"Tennis", b:"Padel"},
  {cat:"Sport", a:"Basket", b:"Pallavolo"},
  {cat:"Sport", a:"Nuoto", b:"Pallanuoto"},
  {cat:"Sport", a:"Formula 1", b:"MotoGP"},
  {cat:"Sport", a:"Sci", b:"Snowboard"},
  {cat:"Sport", a:"Boxe", b:"Kickboxing"},
  {cat:"Sport", a:"Atletica", b:"Triathlon"},
  {cat:"Sport", a:"Golf", b:"Minigolf"},
  {cat:"Sport", a:"Ciclismo", b:"Mountain bike"},
  {cat:"Sport", a:"Ping pong", b:"Tennis"},
  {cat:"Sport", a:"Scherma", b:"Kendo"},
  {cat:"Sport", a:"Baseball", b:"Softball"},
  {cat:"Sport", a:"Hockey", b:"Lacrosse"},
  {cat:"Sport", a:"Surf", b:"Windsurf"},
  {cat:"Sport", a:"Judo", b:"Karate"},
  {cat:"Sport", a:"Skateboard", b:"Pattinaggio"},
  {cat:"Sport", a:"Arrampicata", b:"Alpinismo"},
  {cat:"Sport", a:"Canottaggio", b:"Kayak"},
  {cat:"Sport", a:"Maratona", b:"Mezza maratona"},

  // ANIMALI
  {cat:"Animali", a:"Leone", b:"Tigre"},
  {cat:"Animali", a:"Gatto", b:"Volpe"},
  {cat:"Animali", a:"Cane", b:"Lupo"},
  {cat:"Animali", a:"Mucca", b:"Bufalo"},
  {cat:"Animali", a:"Cavallo", b:"Asino"},
  {cat:"Animali", a:"Aquila", b:"Falco"},
  {cat:"Animali", a:"Delfino", b:"Orca"},
  {cat:"Animali", a:"Squalo", b:"Balena"},
  {cat:"Animali", a:"Pecora", b:"Capra"},
  {cat:"Animali", a:"Rana", b:"Rospo"},
  {cat:"Animali", a:"Coccodrillo", b:"Alligatore"},
  {cat:"Animali", a:"Ghepardo", b:"Leopardo"},
  {cat:"Animali", a:"Topo", b:"Criceto"},
  {cat:"Animali", a:"Oca", b:"Anatra"},
  {cat:"Animali", a:"Pavone", b:"Fagiano"},
  {cat:"Animali", a:"Serpente", b:"Lucertola"},
  {cat:"Animali", a:"Polpo", b:"Calamaro"},
  {cat:"Animali", a:"Granchio", b:"Aragosta"},
  {cat:"Animali", a:"Cinghiale", b:"Maiale"},
  {cat:"Animali", a:"Pinguino", b:"Foca"},

  // CIBO
  {cat:"Cibo e Cucina", a:"Pizza", b:"Focaccia"},
  {cat:"Cibo e Cucina", a:"Pasta", b:"Riso"},
  {cat:"Cibo e Cucina", a:"Lasagna", b:"Cannelloni"},
  {cat:"Cibo e Cucina", a:"Gelato", b:"Granita"},
  {cat:"Cibo e Cucina", a:"Pane", b:"Toast"},
  {cat:"Cibo e Cucina", a:"Cappuccino", b:"Caffè macchiato"},
  {cat:"Cibo e Cucina", a:"Cornetto", b:"Brioche"},
  {cat:"Cibo e Cucina", a:"Risotto", b:"Minestra"},
  {cat:"Cibo e Cucina", a:"Mozzarella", b:"Burrata"},
  {cat:"Cibo e Cucina", a:"Prosciutto", b:"Salame"},
  {cat:"Cibo e Cucina", a:"Parmigiana", b:"Lasagna"},
  {cat:"Cibo e Cucina", a:"Tiramisù", b:"Zuppa inglese"},
  {cat:"Cibo e Cucina", a:"Carbonara", b:"Amatriciana"},
  {cat:"Cibo e Cucina", a:"Hamburger", b:"Hot dog"},
  {cat:"Cibo e Cucina", a:"Sushi", b:"Sashimi"},
  {cat:"Cibo e Cucina", a:"Kebab", b:"Gyros"},
  {cat:"Cibo e Cucina", a:"Piadina", b:"Crêpe"},
  {cat:"Cibo e Cucina", a:"Polenta", b:"Purè"},
  {cat:"Cibo e Cucina", a:"Arancino", b:"Supplì"},
  {cat:"Cibo e Cucina", a:"Cioccolato", b:"Cacao"}

];

const WORD_CATEGORIES = [...new Set(WORD_BANK.map(item => item.cat))];
